// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasourceUrl =
  process.env["PRISMA_MIGRATION_DATABASE_URL"] ??
  process.env["DIRECT_DATABASE_URL"] ??
  process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma ORM 7 nao usa mais `directUrl` no schema/config; a CLI le
    // `datasource.url`. Por isso preferimos a conexao direta quando ela existe.
    //
    // Runtime da aplicacao: o Prisma Client ignora este arquivo e usa
    // DATABASE_URL em lib/db/index.ts, mantendo a conexao pooled do Supavisor.
    //
    // Migrations sao DDL: use `npm run db:migrate:dev` /
    // `npm run db:migrate:deploy`. O wrapper define
    // PRISMA_MIGRATION_DATABASE_URL com DATABASE_SUPERUSER_URL apenas no
    // processo filho.
    url: datasourceUrl,

    // Shadow database usado pelo `migrate dev` para detectar drift.
    //
    // Nao aponte para DATABASE_SUPERUSER_URL: essa URL e o banco principal, e
    // o Prisma recusa usar o proprio banco da aplicacao como shadow. Como o
    // role postgres do Supabase tem CREATEDB, o Prisma cria um shadow
    // temporario automaticamente quando `shadowDatabaseUrl` fica ausente.
    shadowDatabaseUrl: process.env["PRISMA_SHADOW_DATABASE_URL"],
  },
});
