// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Runtime da aplicacao: role restrito, so DML.
    //
    // A CLI do Prisma tambem resolve esta variavel para saber onde aplicar
    // migrations. Como migrations sao DDL, os comandos de migration nao devem
    // ser chamados direto — use `npm run db:migrate:dev` /
    // `npm run db:migrate:deploy`, que passam por scripts/run-with-superuser.mjs
    // e sobrescrevem DATABASE_URL com DATABASE_SUPERUSER_URL no processo filho.
    url: process.env["DATABASE_URL"],

    // Shadow database usado pelo `migrate dev` para detectar drift.
    //
    // Normalmente fica vazio: rodando via run-with-superuser.mjs, o Prisma se
    // conecta como superusuario e cria/derruba um shadow temporario sozinho.
    //
    // Preencha SHADOW_DATABASE_URL apenas se o usuario de migration nao puder
    // criar bancos (CREATEDB). Nesse caso aponte para um banco DEDICADO e
    // vazio: com shadow explicito o Prisma **apaga o schema desse banco** a
    // cada `migrate dev`. Nunca reaproveite aqui a URL do banco da aplicacao.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
